# Generated by Django 4.2.20 on 2025-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('host', 'Host'), ('client', 'Client'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
